export const TEST_IDS = {
  auth: {
    email: 'auth-email',
    password: 'auth-password',
    loginSubmit: 'auth-login-submit',
    error: 'auth-error',
    roleSelect: 'auth-role-select',
  },
  nav: {
    dashboard: 'nav-dashboard',
    patients: 'nav-patients',
    providers: 'nav-providers',
    appointments: 'nav-appointments',
    claims: 'nav-claims',
    uploads: 'nav-uploads',
    logout: 'nav-logout',
    userMenu: 'nav-user-menu',
  },
  chaos: {
    toggle: 'chaos-mode-toggle',
    panel: 'chaos-mode-panel',
    locatorChanges: 'chaos-locator-changes',
    labelChanges: 'chaos-label-changes',
    domRestructure: 'chaos-dom-restructure',
    missingTestIds: 'chaos-missing-testids',
    dynamicRender: 'chaos-dynamic-render',
  },
  toast: {
    container: 'toast-container',
    item: (id: string) => `toast-${id}`,
  },
  dashboard: {
    page: 'dashboard-page',
    statPatients: 'dashboard-stat-patients',
    statAppointments: 'dashboard-stat-appointments',
    statClaims: 'dashboard-stat-claims',
    quickAddPatient: 'dashboard-quick-add-patient',
  },
  patients: {
    page: 'patients-page',
    search: 'patient-search',
    statusFilter: 'patient-status-filter',
    addBtn: 'patient-add-btn',
    table: 'patient-table',
    row: (id: string) => `patient-row-${id}`,
    edit: (id: string) => `patient-edit-${id}`,
    delete: (id: string) => `patient-delete-${id}`,
    modal: 'modal-patient',
    formFirstName: 'patient-form-first-name',
    formLastName: 'patient-form-last-name',
    formMrn: 'patient-form-mrn',
    formDob: 'patient-form-dob',
    formEmail: 'patient-form-email',
    formPhone: 'patient-form-phone',
    formStatus: 'patient-form-status',
    formProvider: 'patient-form-provider',
    formSubmit: 'patient-form-submit',
    formCancel: 'patient-form-cancel',
    confirmDelete: 'patient-confirm-delete',
  },
  providers: {
    page: 'providers-page',
    search: 'provider-search',
    specialtyFilter: 'provider-specialty-filter',
    addBtn: 'provider-add-btn',
    table: 'provider-table',
    row: (id: string) => `provider-row-${id}`,
    edit: (id: string) => `provider-edit-${id}`,
    modal: 'modal-provider',
    formSubmit: 'provider-form-submit',
    formCancel: 'provider-form-cancel',
  },
  appointments: {
    page: 'appointments-page',
    search: 'appointment-search',
    statusFilter: 'appointment-status-filter',
    addBtn: 'appointment-add-btn',
    table: 'appointment-table',
    row: (id: string) => `appointment-row-${id}`,
    edit: (id: string) => `appointment-edit-${id}`,
    modal: 'modal-appointment',
    formSubmit: 'appointment-form-submit',
    formCancel: 'appointment-form-cancel',
  },
  claims: {
    page: 'claims-page',
    search: 'claim-search',
    statusFilter: 'claim-status-filter',
    table: 'claim-table',
    row: (id: string) => `claim-row-${id}`,
    view: (id: string) => `claim-view-${id}`,
    modal: 'modal-claim',
    formSubmit: 'claim-form-submit',
  },
  uploads: {
    page: 'uploads-page',
    dropzone: 'upload-dropzone',
    fileInput: 'upload-file-input',
    patientSelect: 'upload-patient-select',
    submit: 'upload-submit',
    table: 'upload-table',
    row: (id: string) => `upload-row-${id}`,
  },
  table: {
    sort: (col: string) => `table-sort-${col}`,
    paginationPrev: 'table-pagination-prev',
    paginationNext: 'table-pagination-next',
    pageSize: 'table-page-size',
    pageInfo: 'table-page-info',
  },
  modal: {
    close: (name: string) => `modal-${name}-close`,
    overlay: (name: string) => `modal-${name}-overlay`,
  },
} as const;
