import fs from 'node:fs';
import path from 'node:path';
import { CONFIG } from '../config.ts';
import type {
  BindingResult,
  PomLifecycleReport,
  PomMethodReport,
  PomMethodSpec,
} from '../types.ts';
import { ensureDir, relativeToRepo, shortHash, writeText, log } from '../util.ts';

const GEN_OPEN = (name: string, hash: string, selectors: string) =>
  `  // >>> generated:${name} hash=${hash} selectors=${selectors || '-'}`;
const GEN_CLOSE = (name: string) => `  // <<< generated:${name}`;
const CUSTOM_OPEN = '  // >>> custom — hand-written code below is preserved across regeneration';
const CUSTOM_CLOSE = '  // <<< custom';

interface ParsedPom {
  generated: Map<string, { hash: string; block: string }>;
  customInner: string;
}

function fileFor(pageObject: string): string {
  const base = pageObject.replace(/Page$/, '').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  return path.join(CONFIG.pagesDir, `${base}.page.ts`);
}

function bodyHash(spec: PomMethodSpec): string {
  return shortHash(spec.params.join(','), spec.body.join('\n'));
}

/** Render a single generated method block (markers + signature + body). */
function renderMethod(spec: PomMethodSpec): string {
  const hash = bodyHash(spec);
  const params = spec.params.map((p) => `${p}: string`).join(', ');
  const body = spec.body.map((l) => `    ${l}`).join('\n');
  return [
    GEN_OPEN(spec.name, hash, spec.selectorKeys.join(',')),
    `  async ${spec.name}(${params}): Promise<void> {`,
    body,
    '  }',
    GEN_CLOSE(spec.name),
  ].join('\n');
}

/** Extract generated blocks + the custom region from an existing POM file. */
function parseExisting(source: string): ParsedPom {
  const generated = new Map<string, { hash: string; block: string }>();
  const genRe = /^[ \t]*\/\/ >>> generated:(\w+) hash=(\w+)[^\n]*\n([\s\S]*?)^[ \t]*\/\/ <<< generated:\1[ \t]*$/gm;
  let m: RegExpExecArray | null;
  while ((m = genRe.exec(source)) !== null) {
    generated.set(m[1], { hash: m[2], block: m[0] });
  }

  let customInner = '';
  const customRe = /\/\/ >>> custom[^\n]*\n([\s\S]*?)^[ \t]*\/\/ <<< custom[ \t]*$/m;
  const cm = source.match(customRe);
  if (cm) customInner = cm[1].replace(/\s+$/, '');

  return { generated, customInner };
}

function countCustomMethods(customInner: string): number {
  const matches = customInner.match(/\basync\s+\w+\s*\(/g);
  return matches ? matches.length : 0;
}

/**
 * Run the POM lifecycle for every page that the bindings require:
 *   - generate missing page objects / methods
 *   - update generated methods whose locator (body hash) changed
 *   - preserve hand-written code inside the custom region
 */
export function generatePoms(binding: BindingResult): PomLifecycleReport {
  log.step('POM lifecycle — generating / updating page objects');
  ensureDir(CONFIG.pagesDir);

  const byPage = new Map<string, PomMethodSpec[]>();
  for (const spec of binding.requiredMethods) {
    const list = byPage.get(spec.pageObject) ?? [];
    list.push(spec);
    byPage.set(spec.pageObject, list);
  }

  const report: PomLifecycleReport = { generatedAt: new Date().toISOString(), pages: [], methods: [] };

  for (const [pageObject, specs] of [...byPage.entries()].sort()) {
    const file = fileFor(pageObject);
    const exists = fs.existsSync(file);
    const existing = exists ? parseExisting(fs.readFileSync(file, 'utf8')) : { generated: new Map(), customInner: '' };

    let generatedCount = 0;
    let updatedCount = 0;
    const sorted = [...specs].sort((a, b) => a.name.localeCompare(b.name));

    for (const spec of sorted) {
      const prev = existing.generated.get(spec.name);
      const newHash = bodyHash(spec);
      let change: PomMethodReport['change'];
      if (!prev) {
        change = 'generated';
        generatedCount++;
      } else if (prev.hash !== newHash) {
        change = 'updated';
        updatedCount++;
      } else {
        change = 'unchanged';
      }
      report.methods.push({ pageObject, method: spec.name, kind: 'generated', change, selectorKeys: spec.selectorKeys });
    }

    // Preserved custom methods (hand-written, inside the custom region).
    const customMethods = countCustomMethods(existing.customInner);
    if (customMethods > 0) {
      report.methods.push({ pageObject, method: `<${customMethods} custom>`, kind: 'custom', change: 'preserved', selectorKeys: [] });
    }

    const customRegion = [
      CUSTOM_OPEN,
      existing.customInner ? existing.customInner : '  // Add custom helpers here. This region is never overwritten.',
      CUSTOM_CLOSE,
    ].join('\n');

    const out = [
      '// AUTO-GENERATED by Locator Intelligence — POM lifecycle managed.',
      '// Generated method blocks (// >>> generated:NAME) are owned by the toolkit and',
      '// rewritten on regeneration. Hand-written helpers in the custom region are kept.',
      "import { type Page, expect } from '@playwright/test';",
      '',
      `export class ${pageObject} {`,
      '  constructor(public readonly page: Page) {}',
      '',
      sorted.map(renderMethod).join('\n\n'),
      '',
      customRegion,
      '}',
      '',
    ].join('\n');

    writeText(file, out);
    report.pages.push({
      pageObject,
      file: relativeToRepo(file),
      created: !exists,
      generatedMethods: generatedCount,
      updatedMethods: updatedCount,
      customMethods,
    });

    const verb = !exists ? 'created' : `${generatedCount} new, ${updatedCount} updated`;
    log.ok(`${pageObject} (${verb}) → ${relativeToRepo(file)}`);
  }

  return report;
}
