import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import { CONFIG } from '../config.ts';
import type { ExecutionResults, TestResult, TestStatus } from '../types.ts';
import { relativeToRepo, walkFiles, writeJson, writeText, log } from '../util.ts';

const PLAYWRIGHT_CONFIG = `import { defineConfig, devices } from '@playwright/test';

// AUTO-GENERATED by Locator Intelligence. Safe to edit.
export default defineConfig({
  testDir: './tests/generated',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: [['list'], ['json', { outputFile: '.locator-intelligence/playwright-report.json' }]],
  use: {
    baseURL: process.env.LI_BASE_URL ?? 'http://localhost:5173',
    trace: 'on-first-retry',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: {
    command: 'npm run dev',
    url: process.env.LI_BASE_URL ?? 'http://localhost:5173',
    reuseExistingServer: true,
    timeout: 120_000,
  },
});
`;

export function ensurePlaywrightConfig(): void {
  if (!fs.existsSync(CONFIG.playwrightConfigFile)) {
    writeText(CONFIG.playwrightConfigFile, PLAYWRIGHT_CONFIG);
    log.info(`Wrote ${relativeToRepo(CONFIG.playwrightConfigFile)}`);
  }
}

/** Recursively pull test results out of Playwright's JSON reporter output. */
function collectResults(node: unknown, out: TestResult[]): void {
  if (!node || typeof node !== 'object') return;
  const obj = node as Record<string, unknown>;

  if (Array.isArray(obj.suites)) for (const s of obj.suites) collectResults(s, out);
  if (Array.isArray(obj.specs)) {
    for (const spec of obj.specs as Record<string, unknown>[]) {
      const tests = (spec.tests as Record<string, unknown>[]) ?? [];
      for (const t of tests) {
        const results = (t.results as Record<string, unknown>[]) ?? [];
        const last = results[results.length - 1] ?? {};
        out.push({
          spec: String(spec.file ?? ''),
          title: String(spec.title ?? ''),
          status: (last.status as TestStatus) ?? 'unknown',
          durationMs: Number(last.duration ?? 0),
          error: last.error ? String((last.error as Record<string, unknown>).message ?? '') : undefined,
        });
      }
    }
  }
}

/** Build a placeholder result set when Playwright cannot run. */
function simulatedResults(note: string): ExecutionResults {
  const specFiles = walkFiles(CONFIG.generatedSpecsDir, ['.spec.ts']);
  const results: TestResult[] = [];
  for (const file of specFiles) {
    const text = fs.readFileSync(file, 'utf8');
    const titles = [...text.matchAll(/\btest(?:\.fixme)?\(\s*"([^"]+)"/g)].map((m) => m[1]);
    for (const title of titles) {
      results.push({ spec: relativeToRepo(file), title, status: 'skipped', durationMs: 0 });
    }
  }
  return {
    ranAt: new Date().toISOString(),
    mode: 'skipped',
    total: results.length,
    passed: 0,
    failed: 0,
    skipped: results.length,
    note,
    results,
  };
}

/** Run the generated specs against the real app (best effort). */
export function execute(): ExecutionResults {
  log.step('Execute — running generated specs with Playwright');
  ensurePlaywrightConfig();

  const run = spawnSync(
    process.platform === 'win32' ? 'npx.cmd' : 'npx',
    ['playwright', 'test', '--config', CONFIG.playwrightConfigFile],
    { cwd: CONFIG.repoRoot, encoding: 'utf8', timeout: 240_000 }
  );

  let result: ExecutionResults;

  const reportPath = `${CONFIG.dataDir}/playwright-report.json`;
  if (run.error || run.status === null) {
    const note =
      'Playwright did not run (binary or browsers unavailable). Run `npm i -D @playwright/test && npx playwright install` to enable real execution.';
    log.warn(note);
    result = simulatedResults(note);
  } else if (fs.existsSync(reportPath)) {
    const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
    const results: TestResult[] = [];
    collectResults(report, results);
    result = {
      ranAt: new Date().toISOString(),
      mode: 'playwright',
      command: 'npx playwright test',
      total: results.length,
      passed: results.filter((r) => r.status === 'passed').length,
      failed: results.filter((r) => r.status === 'failed' || r.status === 'timedOut').length,
      skipped: results.filter((r) => r.status === 'skipped').length,
      results,
    };
  } else {
    const note = 'Playwright ran but produced no JSON report; treating specs as not executed.';
    log.warn(note);
    result = simulatedResults(note);
  }

  writeJson(CONFIG.executionResultsFile, result);
  log.ok(`Execution (${result.mode}): ${result.passed} passed, ${result.failed} failed, ${result.skipped} skipped`);
  log.info(`Results → ${relativeToRepo(CONFIG.executionResultsFile)}`);
  return result;
}
